name: fp_util
description: Utilities and Extensions for num,BuildContext,EdgeInsets,File,String. constants for horizontal and vertical spacing.

version: 3.2.0
homepage: https://docs.kishormainali.com/
repository: https://github.com/kishormainali/fp_util
issue_tracker: https://github.com/kishormainali/fp_util/issues
topics:
  - extensions
  - tags-input-field
  - utilities
  - spacing
  - widgets

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  mime: ^2.0.0

  # image picker
  image_picker: ^1.1.2

  # file picker
  file_picker: ^8.1.3

  # svg
  flutter_svg: ^2.0.10+1

  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  path: ^1.9.0
  intl: ^0.19.0

  equatable: ^2.0.5

  mask_text_input_formatter: ^2.9.0

  gap: ^3.0.1

  uuid: ^4.5.1

  flutter_animate: ^4.5.0

  collection: 1.18.0

  dio: ^5.7.0

  ansicolor: ^2.0.3

  fp_logger: ^1.0.10

dev_dependencies:
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/full_logo.png
